name: Xunit Tests
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1

      - name: Build and Test
        run: |
          dotnet build
          dotnet test --logger "html;logfilename=testResults.html" --results-directory TestResults --collect:"XPlat Code Coverage"

      - name: Convert HTML to Image
        uses: getsentry/action-html-to-image
        with:
          input_file: 'TestResults/testResults.html'
          output_file: 'TestResults/testResults.png'
          width: '1200'
          height: '900'

      - name: Publish Xunit Results
        uses: actions/upload-artifact@v2
        with:
          name: TestResults
          path: TestResults

      - name: Publish Image as Artifact
        uses: actions/upload-artifact@v2
        with:
          name: TestImage
          path: TestResults/testResults.png
